#! /bin/zsh

export MY_MAIL="YOUR_EMAIL"
export SECURTIYCODE="YOUR_GOOGLE_APPLICATION_PASSWORD"

export SECTION="DESIRED_SECTION"
export QUEST="KEYWORD_TO_BE_SEARCH"
export ATTACH_LINK="LINK_YOU_WANT_TO_ATTACH_IN_MAIL"

python3 Curl_GoShare.py